# Generated by Django 2.1.5 on 2019-01-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ktp_number', models.CharField(max_length=14)),
                ('birthdate', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('mobile_phone', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('office_name', models.CharField(max_length=50)),
                ('office_phone', models.CharField(max_length=10)),
                ('sibling_name', models.CharField(max_length=200)),
                ('sibling_phone', models.CharField(max_length=10)),
            ],
        ),
    ]
