# Generated by Django 2.1.5 on 2019-01-09 07:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kreditplus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapplication',
            name='month_installment',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formapplication',
            name='order_number',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formapplication',
            name='order_price',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=19),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formapplication',
            name='birthdate',
            field=models.DateField(default=0),
        ),
    ]
