# Generated by Django 2.1.5 on 2019-01-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kreditplus', '0003_auto_20190109_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapplication',
            name='month_installment',
            field=models.IntegerField(default=0),
        ),
    ]
