# Generated by Django 2.1.5 on 2019-01-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kreditplus', '0004_auto_20190109_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapplication',
            name='order_number',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='formapplication',
            name='order_price',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=19),
        ),
    ]
